[package]
name = "json-pam"
version = "1.0.0"
edition = "2021"

[dependencies]
#pam = "0.8"
pam = { path = "../pam-rust" }
rpassword = "7.3.1"
uzers = "0.11.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
libc = "*"
